# ==============================================================================
# Merge external variant annotation scores
#
# Purpose:
#   Merge ANNOVAR-derived variant scores and population allele frequencies
#   back into the annotated PTC variant dataset.
#
# Input:
#   1. Annotated PTC variant dataset
#   2. ANNOVAR multianno output generated by:
#        06b_run_variant_scores.sh
#
# Features added:
#   - CADD_raw
#   - CADD_phred
#   - gnomAD_exome_ALL
#
# Shared across:
#   TOPMed, gnomAD, ClinVar, GREGoR
# ==============================================================================

library(dplyr)


# ------------------------------------------------------------------------------
# 1. Configuration
# ------------------------------------------------------------------------------

CONFIG <- list(

    variant_file =
        "/path/to/annotated_variants.rds",

    score_file =
        "/path/to/variants_external_annotation.hg38_multianno.txt",

    output_file =
        "/path/to/variant_annotation_scores.rds"
)


# ------------------------------------------------------------------------------
# 2. Load data
# ------------------------------------------------------------------------------

variants <- readRDS(
    CONFIG$variant_file
)

scores <- read.delim(
    CONFIG$score_file,
    stringsAsFactors = FALSE,
    check.names = FALSE,
    na.strings = c(".", "NA", "")
)

# ------------------------------------------------------------------------------
# 3. Construct standardized variant key
#
# Format:
#   chr7:127588544_A>T
# ------------------------------------------------------------------------------

scores$key <- with(
    scores,
    paste0(
        ifelse(
            grepl("^chr", Chr),
            "",
            "chr"
        ),
        Chr,
        ":",
        Start,
        "_",
        Ref,
        ">",
        Alt
    )
)


# ------------------------------------------------------------------------------
# 4. Select features used in the analysis
# ------------------------------------------------------------------------------

scores_to_merge <- scores %>%
    select(
        key,
        CADD_raw,
        CADD_phred,
        gnomAD_exome_ALL
    ) %>%
    distinct(
        key,
        .keep_all = TRUE
    )


# ------------------------------------------------------------------------------
# 5. Merge with variant dataset
# ------------------------------------------------------------------------------

variants_with_scores <- variants %>%
    left_join(
        scores_to_merge,
        by = "key"
    )


# ------------------------------------------------------------------------------
# 6. QC
# ------------------------------------------------------------------------------

message(
    "Input variants: ",
    nrow(variants)
)

message(
    "Variants after merge: ",
    nrow(variants_with_scores)
)

message(
    "CADD annotation available: ",
    sum(
        !is.na(
            variants_with_scores$CADD_phred
        )
    ),
    " / ",
    nrow(variants_with_scores)
)

message(
    "gnomAD exome AF available: ",
    sum(
        !is.na(
            variants_with_scores$gnomAD_exome_ALL
        )
    ),
    " / ",
    nrow(variants_with_scores)
)


# The left join should not change the number of variants.
stopifnot(
    nrow(variants_with_scores) ==
        nrow(variants)
)


# ------------------------------------------------------------------------------
# 7. Save feature table
# ------------------------------------------------------------------------------

variant_annotation_scores <- variants_with_scores %>%
    select(
        key,
        CADD_raw,
        CADD_phred,
        gnomAD_exome_ALL
    )

saveRDS(
    variant_annotation_scores,
    CONFIG$output_file
)

message(
    "Variant annotation score table saved: ",
    CONFIG$output_file
)
