"""
07b_FIMO_motif_features.py

RBP motif scanning and feature-matrix generation using FIMO.

Purpose
-------
Scan the PTC-centered sequence regions generated by
07a_motif_region_extraction.py for RNA-binding protein (RBP) motifs
and convert significant motif occurrences into binary predictive features.

This workflow is designed to be shared across:
    - TOPMed
    - gnomAD
    - ClinVar
    - GREGoR

External software
-----------------
MEME Suite version:
    5.5.5

FIMO:
    FIMO distributed with MEME Suite v5.5.5

Significance threshold:
    p < 1e-4

Motif resources
---------------
MOTIFS:
    MEME-formatted motif file used for FIMO scanning.

ATTRACT:
    Human ATtRACT motif annotation table used to map motif matrix IDs
    to RNA-binding protein gene symbols.

Input
-----
1. FASTA batches generated by:
       07a_motif_region_extraction.py

2. Variant sequence table generated by:
       07a_motif_region_extraction.py

3. MEME-formatted motif file:
       memefile.txt

4. ATtRACT human motif annotation:
       ATtRACT_db_human.txt

Regions analyzed
----------------
utr3_all
utr3_200
ptc_to_ejc
newutr_all
newutr_200
ptc_pm100
ejc_pm100

Output
------
1. all_fimo_hits.csv
       All significant FIMO motif occurrences across all regions.

2. motif_presence_matrix.csv
       Binary region-by-RBP feature matrix.

Feature naming convention
-------------------------
<region>.<RBP>

Examples:
    ptc_to_ejc.PTBP1
    newutr_all.HNRNPC
    utr3_200.SRSF1

Binary encoding
---------------
1 = at least one significant motif occurrence
0 = no significant motif occurrence

The output matrix is keyed by the standardized genomic variant `key`
and can therefore be merged directly into the final feature matrix.
"""

import os
import subprocess
from pathlib import Path
from multiprocessing import Pool

import numpy as np
import pandas as pd


# ==============================================================================
# 1. Configuration
# ==============================================================================

WORKDIR = Path("/path/to/project")

# Output from 07a_motif_region_extraction.py
SEQUENCE_CSV = (
    WORKDIR
    / "variants_with_motif_regions.csv"
)

FASTA_DIR = (
    WORKDIR
    / "motif_regions"
)

# Motif resources
MOTIFS = (
    WORKDIR
    / "reference"
    / "motifs"
    / "memefile.txt"
)

ATTRACT = (
    WORKDIR
    / "reference"
    / "motifs"
    / "ATtRACT_db_human.txt"
)

OUTPUT_DIR = (
    WORKDIR
    / "motif_results"
)

# Manuscript analysis settings
EXPECTED_FIMO_VERSION = "5.5.5"
FIMO_THRESHOLD = 1e-4
FIMO_TIMEOUT = 7200

# Parallel FIMO jobs
N_CORES = 6

REGIONS = [
    "utr3_all",
    "utr3_200",
    "ptc_to_ejc",
    "newutr_all",
    "newutr_200",
    "ptc_pm100",
    "ejc_pm100",
]


# ==============================================================================
# 2. Environment checks
# ==============================================================================

def check_required_files():
    """
    Confirm that required input files and directories exist.
    """

    required_files = {
        "Sequence table": SEQUENCE_CSV,
        "MEME motif file": MOTIFS,
        "ATtRACT annotation": ATTRACT,
    }

    for label, path in required_files.items():

        if not path.exists():

            raise FileNotFoundError(
                f"{label} not found: {path}"
            )

    if not FASTA_DIR.exists():

        raise FileNotFoundError(
            f"FASTA directory not found: {FASTA_DIR}"
        )


def check_fimo():
    """
    Confirm that FIMO is installed and report its version.

    The manuscript analysis used MEME Suite / FIMO version 5.5.5.
    A different version generates a warning rather than stopping the run.
    """

    try:

        result = subprocess.run(
            ["fimo", "--version"],
            capture_output=True,
            text=True,
            check=False
        )

    except FileNotFoundError as exc:

        raise RuntimeError(
            "FIMO was not found on PATH. "
            "Install MEME Suite v5.5.5 and ensure `fimo` "
            "is available from the command line."
        ) from exc

    if result.returncode != 0:

        raise RuntimeError(
            "FIMO could not be executed.\n"
            f"STDERR:\n{result.stderr}"
        )

    version = (
        result.stdout.strip()
        or
        result.stderr.strip()
    )

    print(
        "Detected FIMO version:",
        version
    )

    if EXPECTED_FIMO_VERSION not in version:

        print(
            "WARNING: The manuscript analysis used "
            f"MEME Suite/FIMO {EXPECTED_FIMO_VERSION}. "
            "Using another version may affect exact reproducibility."
        )


# ==============================================================================
# 3. FASTA identifier handling
# ==============================================================================

def make_safe_fasta_id(key):
    """
    Convert the standardized genomic variant key into the FASTA identifier
    format used by 07a_motif_region_extraction.py.

    Example
    -------
    chr7:127588544_A>T
        ->
    chr7_127588544_A_T
    """

    return (
        str(key)
        .replace(":", "_")
        .replace(">", "_")
        .replace("/", "_")
        .replace(" ", "_")
    )


def build_fasta_id_map(variants):
    """
    Create a mapping from FASTA sequence identifier back to the original
    standardized variant key.
    """

    mapping = {}

    for key in variants["key"]:

        fasta_id = make_safe_fasta_id(
            key
        )

        if fasta_id in mapping:

            raise ValueError(
                "Duplicate FASTA identifier generated for variant keys: "
                f"{fasta_id}"
            )

        mapping[fasta_id] = key

    return mapping


# ==============================================================================
# 4. Run FIMO for one FASTA batch
# ==============================================================================

def run_fimo_batch(args):
    """
    Run FIMO on one FASTA batch for one sequence region.
    """

    region, fasta_path, outdir = args

    outdir.mkdir(
        parents=True,
        exist_ok=True
    )

    cmd = [
        "fimo",
        "--thresh",
        str(FIMO_THRESHOLD),
        "--oc",
        str(outdir),
        str(MOTIFS),
        str(fasta_path),
    ]

    try:

        subprocess.run(
            cmd,
            check=True,
            timeout=FIMO_TIMEOUT,
            capture_output=True,
            text=True
        )

        fimo_file = (
            outdir
            / "fimo.tsv"
        )

        if not fimo_file.exists():

            print(
                "No fimo.tsv found:",
                fasta_path
            )

            return pd.DataFrame()

        hits = pd.read_csv(
            fimo_file,
            sep="\t",
            comment="#"
        )

        if hits.empty:
            return pd.DataFrame()

        hits["region"] = region

        return hits

    except subprocess.TimeoutExpired:

        print(
            "FIMO timeout:",
            fasta_path
        )

        return pd.DataFrame()

    except subprocess.CalledProcessError as exc:

        print(
            "FIMO error:",
            fasta_path
        )

        print(
            exc.stderr
        )

        return pd.DataFrame()


# ==============================================================================
# 5. Run FIMO across all regions
# ==============================================================================

def run_fimo():
    """
    Run FIMO across all FASTA batches and sequence regions.
    """

    print(
        "\nRunning FIMO motif scans...\n"
    )

    tasks = []

    results_dir = (
        OUTPUT_DIR
        / "fimo_hits"
    )

    for region in REGIONS:

        region_dir = (
            FASTA_DIR
            / region
        )

        if not region_dir.exists():

            print(
                f"WARNING: Region directory missing: {region_dir}"
            )

            continue

        batches = sorted(
            region_dir.glob(
                "batch_*/seqs.fasta"
            )
        )

        print(
            f"{region}: "
            f"{len(batches)} FASTA batches"
        )

        for fasta_path in batches:

            batch_name = (
                fasta_path
                .parent
                .name
            )

            outdir = (
                results_dir
                / region
                / batch_name
            )

            tasks.append(
                (
                    region,
                    fasta_path,
                    outdir
                )
            )

    if not tasks:

        raise RuntimeError(
            "No FASTA batches were found for motif scanning."
        )

    with Pool(
        processes=N_CORES
    ) as pool:

        result_tables = pool.map(
            run_fimo_batch,
            tasks
        )

    result_tables = [
        table
        for table in result_tables
        if not table.empty
    ]

    if not result_tables:

        print(
            "WARNING: No significant FIMO hits were detected."
        )

        return pd.DataFrame()

    all_hits = pd.concat(
        result_tables,
        ignore_index=True
    )

    hits_file = (
        OUTPUT_DIR
        / "all_fimo_hits.csv"
    )

    all_hits.to_csv(
        hits_file,
        index=False
    )

    print(
        "Saved FIMO hits:",
        hits_file
    )

    print(
        "Total significant motif occurrences:",
        len(all_hits)
    )

    return all_hits


# ==============================================================================
# 6. Load ATtRACT motif-to-RBP mapping
# ==============================================================================

def load_attract_mapping():
    """
    Load the ATtRACT human motif annotation table and construct a mapping
    from motif matrix identifier to RBP gene symbol.
    """

    attract = pd.read_csv(
        ATTRACT,
        sep="\t"
    )

    required_columns = {
        "Matrix_id",
        "Gene_name",
    }

    missing = (
        required_columns
        -
        set(
            attract.columns
        )
    )

    if missing:

        raise ValueError(
            "ATtRACT table is missing required columns: "
            +
            ", ".join(
                sorted(missing)
            )
        )

    attract = (
        attract[
            [
                "Matrix_id",
                "Gene_name"
            ]
        ]
        .dropna()
        .drop_duplicates()
    )

    id_to_gene = dict(
        zip(
            attract["Matrix_id"],
            attract["Gene_name"]
        )
    )

    return id_to_gene


# ==============================================================================
# 7. Map FIMO motif IDs to RBP genes
# ==============================================================================

def map_motif_to_gene(
    motif_id,
    id_to_gene
):
    """
    Map a FIMO motif identifier to an RBP gene symbol using ATtRACT.

    Some motif identifiers may contain suffixes separated by ':'.
    The prefix is therefore also checked.
    """

    motif_id = str(
        motif_id
    )

    if motif_id in id_to_gene:

        return id_to_gene[
            motif_id
        ]

    motif_prefix = (
        motif_id
        .split(":")[0]
    )

    if motif_prefix in id_to_gene:

        return id_to_gene[
            motif_prefix
        ]

    return ""


# ==============================================================================
# 8. Build binary motif feature matrix
# ==============================================================================

def build_matrix(
    hits,
    variants
):
    """
    Convert significant FIMO motif occurrences into a binary
    region-by-RBP feature matrix.

    Rows:
        variants

    Columns:
        <region>.<RBP>

    Values:
        1 = one or more significant motif occurrences
        0 = no significant motif occurrence
    """

    print(
        "\nBuilding binary motif feature matrix...\n"
    )

    fasta_id_to_key = build_fasta_id_map(
        variants
    )

    id_to_gene = load_attract_mapping()

    # --------------------------------------------------------------------------
    # Handle case where FIMO produced no hits
    # --------------------------------------------------------------------------

    if hits.empty:

        print(
            "No FIMO hits available. "
            "Returning key-only matrix."
        )

        return pd.DataFrame(
            {
                "key":
                    variants["key"]
            }
        )

    # --------------------------------------------------------------------------
    # FIMO uses the FASTA identifier as sequence_name.
    # Convert this back to the standardized variant key.
    # --------------------------------------------------------------------------

    if "sequence_name" not in hits.columns:

        raise ValueError(
            "FIMO output does not contain a `sequence_name` column."
        )

    hits["key"] = (
        hits["sequence_name"]
        .map(
            fasta_id_to_key
        )
    )

    unmapped_sequences = (
        hits["key"]
        .isna()
        .sum()
    )

    if unmapped_sequences > 0:

        print(
            "WARNING:",
            unmapped_sequences,
            "FIMO hits could not be mapped back to a variant key."
        )

    hits = hits[
        hits["key"].notna()
    ].copy()

    # --------------------------------------------------------------------------
    # Map motif matrix IDs to RBP genes
    # --------------------------------------------------------------------------

    hits["gene"] = (
        hits["motif_id"]
        .apply(
            lambda motif_id:
                map_motif_to_gene(
                    motif_id,
                    id_to_gene
                )
        )
    )

    unmapped_motifs = (
        hits["gene"] ==
        ""
    ).sum()

    if unmapped_motifs > 0:

        print(
            "WARNING:",
            unmapped_motifs,
            "motif hits could not be mapped to an ATtRACT RBP gene."
        )

    hits = hits[
        hits["gene"] != ""
    ].copy()

    if hits.empty:

        print(
            "No motif hits remained after ATtRACT mapping."
        )

        return pd.DataFrame(
            {
                "key":
                    variants["key"]
            }
        )

    # --------------------------------------------------------------------------
    # Create final feature name
    # --------------------------------------------------------------------------

    hits["feature"] = (
        hits["region"]
        + "."
        + hits["gene"]
    )

    # --------------------------------------------------------------------------
    # Create complete feature universe
    #
    # Preserve the original workflow logic:
    # every RBP detected anywhere is represented across all seven regions.
    # --------------------------------------------------------------------------

    genes = sorted(
        hits["gene"]
        .unique()
    )

    feature_columns = [
        f"{region}.{gene}"
        for region in REGIONS
        for gene in genes
    ]

    matrix = pd.DataFrame(
        0,
        index=variants["key"],
        columns=feature_columns,
        dtype=np.int8
    )

    matrix.index.name = "key"

    # --------------------------------------------------------------------------
    # Set presence to 1
    # --------------------------------------------------------------------------

    unique_hits = (
        hits[
            [
                "key",
                "feature"
            ]
        ]
        .drop_duplicates()
    )

    for row in unique_hits.itertuples(
        index=False
    ):

        key = row.key
        feature = row.feature

        if (
            key in matrix.index
            and
            feature in matrix.columns
        ):

            matrix.at[
                key,
                feature
            ] = 1

    matrix = (
        matrix
        .reset_index()
    )

    # --------------------------------------------------------------------------
    # QC
    # --------------------------------------------------------------------------

    print(
        "Variants in motif matrix:",
        len(matrix)
    )

    print(
        "RBP genes represented:",
        len(genes)
    )

    print(
        "Motif feature columns:",
        len(feature_columns)
    )

    return matrix


# ==============================================================================
# 9. Save motif feature matrix
# ==============================================================================

def save_matrix(
    matrix
):
    """
    Save binary motif-presence feature matrix.
    """

    matrix_file = (
        OUTPUT_DIR
        / "motif_presence_matrix.csv"
    )

    matrix.to_csv(
        matrix_file,
        index=False
    )

    print(
        "Saved motif feature matrix:",
        matrix_file
    )

    return matrix_file


# ==============================================================================
# 10. Main workflow
# ==============================================================================

def main():

    # --------------------------------------------------------------------------
    # Create output directory
    # --------------------------------------------------------------------------

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    # --------------------------------------------------------------------------
    # Check dependencies and files
    # --------------------------------------------------------------------------

    check_required_files()
    check_fimo()

    # --------------------------------------------------------------------------
    # Load variant table
    # --------------------------------------------------------------------------

    variants = pd.read_csv(
        SEQUENCE_CSV,
        low_memory=False
    )

    if "key" not in variants.columns:

        raise ValueError(
            "Input sequence table must contain a `key` column."
        )

    if variants["key"].duplicated().any():

        duplicated = (
            variants.loc[
                variants["key"].duplicated(),
                "key"
            ]
            .head()
            .tolist()
        )

        raise ValueError(
            "Variant keys must be unique before motif feature generation. "
            f"Examples of duplicated keys: {duplicated}"
        )

    print(
        "Variants loaded:",
        len(variants)
    )

    # --------------------------------------------------------------------------
    # Run FIMO
    # --------------------------------------------------------------------------

    hits = run_fimo()

    # --------------------------------------------------------------------------
    # Build binary motif matrix
    # --------------------------------------------------------------------------

    matrix = build_matrix(
        hits,
        variants
    )

    # --------------------------------------------------------------------------
    # Save output
    # --------------------------------------------------------------------------

    matrix_file = save_matrix(
        matrix
    )

    # --------------------------------------------------------------------------
    # Final summary
    # --------------------------------------------------------------------------

    print(
        "\nMotif feature generation complete."
    )

    print(
        "Output:",
        matrix_file
    )

    print(
        "Next step:"
    )

    print(
        "Merge motif_presence_matrix.csv "
        "into the final feature matrix by `key`."
    )


# ==============================================================================
# 11. Entry point
# ==============================================================================

if __name__ == "__main__":
    main()
