# ==============================================================================
# 99_build_feature_matrix.R
#
# Purpose
# -------
# Assemble the feature tables generated by the scripts in Features/ into the
# final variant-level feature matrix used for NMD prediction.
#
# This script does not generate new biological features. It merges the outputs
# of the individual feature-generation modules using the standardized variant
# identifier (`key`) and performs final quality-control checks.
#
# For the TOPMed model-development dataset, this workflow should reproduce the
# feature matrix used for model training:
#
#     5,749 variants x 853 features
#
# The same feature definitions can subsequently be applied to gnomAD, ClinVar,
# and GREGoR.
#
# Inputs
# ------
# 1. Annotated/filtered variant dataset
# 2. GENCODE v26 sequence features
# 3. PTBP1 binding features
# 4. PTC amino-acid context features
# 5. Gene-level features
# 6. PTC geometry features
# 7. Variant-level scores (CADD, REVEL, allele frequency)
# 8. FIMO/RBP motif features
# 9. Codon optimality features
# 10. Conservation features
# 11. EJC occupancy features
# 12. Downstream AUG/Kozak features
# 13. Readthrough features
#
# Output
# ------
# Final variant-level feature table used as input for model development.
#
# IMPORTANT
# ---------
# Feature inclusion, exclusion, naming, and ordering should match the feature
# set used in the original model-development analysis.
# ==============================================================================


# ------------------------------------------------------------------------------
# 1. Packages
# ------------------------------------------------------------------------------

library(dplyr)
library(readr)


# ------------------------------------------------------------------------------
# 2. Configuration
# ------------------------------------------------------------------------------

config <- list(

  base_variants =
    "output/TOPMed_filtered_variants.rds",

  gencode_features =
    "output/features/01_GENCODEv26_sequence_features.rds",

  ptbp1_features =
    "output/features/02_PTBP1_binding_features.rds",

  amino_acid_features =
    "output/features/03_PTC_amino_acid_context.rds",

  gene_features =
    "output/features/04_gene_level_features.rds",

  ptc_geometry_features =
    "output/features/05_PTC_geometry_derived_features.rds",

  variant_scores =
    "output/features/06_variant_scores.rds",

  motif_features =
    "output/features/07_FIMO_motif_features.rds",

  codon_optimality_features =
    "output/features/08_codon_optimality_features.rds",

  conservation_features =
    "output/features/09_conservation_features.rds",

  ejc_features =
    "output/features/10_EJC_occupancy_features.rds",

  aug_features =
    "output/features/11_PTC_AUG_features.rds",

  readthrough_features =
    "output/features/12_readthrough_features.rds",

  output =
    "output/TOPMed_feature_matrix.rds"
)


# ------------------------------------------------------------------------------
# 3. Helper functions
# ------------------------------------------------------------------------------

check_key <- function(x, object_name) {

  if (!"key" %in% names(x)) {
    stop(object_name, " does not contain the required `key` column.")
  }

  if (anyDuplicated(x$key) > 0) {
    stop(object_name, " contains duplicated variant keys.")
  }

  message(
    object_name,
    ": ",
    nrow(x),
    " variants; ",
    ncol(x),
    " columns"
  )
}


# ------------------------------------------------------------------------------
# 4. Load base variant dataset
# ------------------------------------------------------------------------------

df <- readRDS(config$base_variants)

check_key(df, "Base variant dataset")


# ------------------------------------------------------------------------------
# 5. Load feature tables
# ------------------------------------------------------------------------------

feature_tables <- list(

  GENCODE =
    readRDS(config$gencode_features),

  PTBP1 =
    readRDS(config$ptbp1_features),

  amino_acid =
    readRDS(config$amino_acid_features),

  gene =
    readRDS(config$gene_features),

  PTC_geometry =
    readRDS(config$ptc_geometry_features),

  variant_scores =
    readRDS(config$variant_scores),

  motifs =
    readRDS(config$motif_features),

  codon_optimality =
    readRDS(config$codon_optimality_features),

  conservation =
    readRDS(config$conservation_features),

  EJC =
    readRDS(config$ejc_features),

  AUG =
    readRDS(config$aug_features),

  readthrough =
    readRDS(config$readthrough_features)
)


# ------------------------------------------------------------------------------
# 6. Check feature tables before merging
# ------------------------------------------------------------------------------

for (nm in names(feature_tables)) {
  check_key(feature_tables[[nm]], nm)
}


# ------------------------------------------------------------------------------
# 7. Merge feature tables
# ------------------------------------------------------------------------------

feature_matrix <- df

for (nm in names(feature_tables)) {

  message("Merging: ", nm)

  n_before <- nrow(feature_matrix)

  feature_matrix <- feature_matrix %>%
    left_join(
      feature_tables[[nm]],
      by = "key"
    )

  if (nrow(feature_matrix) != n_before) {
    stop(
      "Row count changed while merging ",
      nm,
      ". Check for duplicated keys."
    )
  }
}


# ------------------------------------------------------------------------------
# 8. Quality control
# ------------------------------------------------------------------------------

message("")
message("Final assembled dataset")
message("-----------------------")
message("Variants: ", nrow(feature_matrix))
message("Columns:  ", ncol(feature_matrix))


# Missingness by feature
missingness <- data.frame(
  feature = names(feature_matrix),
  n_missing = sapply(feature_matrix, function(x) sum(is.na(x))),
  pct_missing = sapply(
    feature_matrix,
    function(x) round(mean(is.na(x)) * 100, 2)
  )
)

missingness <- missingness %>%
  arrange(desc(pct_missing))

write.csv(
  missingness,
  "output/TOPMed_feature_missingness.csv",
  row.names = FALSE
)


# ------------------------------------------------------------------------------
# 9. Check expected TOPMed dimensions
# ------------------------------------------------------------------------------

# These values correspond to the model-development dataset reported in the
# manuscript. Keep this check only after confirming that this script contains
# exactly the same columns that entered model training.

expected_variants <- 5749
expected_features <- 853

message("")
message(
  "Expected model-development matrix: ",
  expected_variants,
  " variants x ",
  expected_features,
  " features"
)

message(
  "Current assembled table: ",
  nrow(feature_matrix),
  " rows x ",
  ncol(feature_matrix),
  " columns"
)


# ------------------------------------------------------------------------------
# 10. Save assembled table
# ------------------------------------------------------------------------------

saveRDS(
  feature_matrix,
  config$output
)

message("")
message("Saved assembled feature table to:")
message(config$output)
