# ==============================================================================
# 99_build_core_feature_table.R
#
# Purpose
# -------
# Assemble the core biological feature tables generated by feature modules
# 01-07 into one variant-level table for each dataset.
#
# Shared across:
#   - TOPMed
#   - gnomAD
#   - ClinVar
#   - GREGoR
#
# Included feature modules
# ------------------------
# 01. GENCODE v26 sequence features
# 02. PTBP1 binding features
# 03. PTC amino-acid context features
# 04. Gene-level features
# 05. PTC geometry features
# 06. Variant-level scores
# 07. FIMO / RBP motif features
#
# NOT included here
# -----------------
# The following specialized feature families remain separate:
#
# 08. Codon optimality
# 09. Conservation
# 10. EJC occupancy
# 11. Downstream AUG / Kozak features
# 12. Readthrough features
#
# For TOPMed, those files are merged later by:
#
#   Model/TrunCat/notebooks/01_data_loading_and_merging.ipynb
#
# Output
# ------
# For each dataset:
#
#   output/<dataset>/<dataset>_core_features.csv
#
# For TOPMed only, the same table is additionally written to:
#
#   Model/TrunCat/data/TOPMed_stopgain.csv
#
# This provides the main TOPMed input expected by the TrunCat modeling
# workflow.
#
# No model-specific feature cleaning or selection is performed here.
# ==============================================================================


# ------------------------------------------------------------------------------
# 1. Required packages
# ------------------------------------------------------------------------------

library(dplyr)
library(readr)


# ------------------------------------------------------------------------------
# 2. Dataset selection
# ------------------------------------------------------------------------------

DATASET <- "TOPMed"

# Allowed values:
#
#   "TOPMed"
#   "gnomAD"
#   "ClinVar"
#   "GREGoR"

allowed_datasets <- c(
    "TOPMed",
    "gnomAD",
    "ClinVar",
    "GREGoR"
)

if (!DATASET %in% allowed_datasets) {

    stop(
        "DATASET must be one of: ",
        paste(
            allowed_datasets,
            collapse = ", "
        )
    )
}


# ------------------------------------------------------------------------------
# 3. Configuration
# ------------------------------------------------------------------------------

config <- list(

    # --------------------------------------------------------------------------
    # Base filtered variant table
    #
    # Output from:
    # Annotation/04_shared_variant_filtering.R
    # --------------------------------------------------------------------------

    base_variants =
        file.path(
            "output",
            DATASET,
            paste0(
                DATASET,
                "_filtered_variants.rds"
            )
        ),


    # --------------------------------------------------------------------------
    # Feature module 01
    # --------------------------------------------------------------------------

    gencode_features =
        file.path(
            "output",
            DATASET,
            "features",
            "01_GENCODEv26_sequence_features.rds"
        ),


    # --------------------------------------------------------------------------
    # Feature module 02
    # --------------------------------------------------------------------------

    ptbp1_features =
        file.path(
            "output",
            DATASET,
            "features",
            "02_PTBP1_binding_features.rds"
        ),


    # --------------------------------------------------------------------------
    # Feature module 03
    # --------------------------------------------------------------------------

    amino_acid_features =
        file.path(
            "output",
            DATASET,
            "features",
            "03_PTC_amino_acid_context.rds"
        ),


    # --------------------------------------------------------------------------
    # Feature module 04
    # --------------------------------------------------------------------------

    gene_features =
        file.path(
            "output",
            DATASET,
            "features",
            "04_gene_level_features.rds"
        ),


    # --------------------------------------------------------------------------
    # Feature module 05
    # --------------------------------------------------------------------------

    ptc_geometry_features =
        file.path(
            "output",
            DATASET,
            "features",
            "05_PTC_geometry_derived_features.rds"
        ),


    # --------------------------------------------------------------------------
    # Feature module 06
    # --------------------------------------------------------------------------

    variant_scores =
        file.path(
            "output",
            DATASET,
            "features",
            "06_variant_scores.rds"
        ),


    # --------------------------------------------------------------------------
    # Feature module 07
    # --------------------------------------------------------------------------

    motif_features =
        file.path(
            "output",
            DATASET,
            "features",
            "07_FIMO_motif_features.rds"
        ),


    # --------------------------------------------------------------------------
    # Dataset-specific core output
    # --------------------------------------------------------------------------

    output =
        file.path(
            "output",
            DATASET,
            paste0(
                DATASET,
                "_core_features.csv"
            )
        )
)


# ------------------------------------------------------------------------------
# 4. Helper: check that a file exists
# ------------------------------------------------------------------------------

check_file <- function(
    path,
    label
) {

    if (!file.exists(path)) {

        stop(
            label,
            " file not found: ",
            path
        )
    }
}


# ------------------------------------------------------------------------------
# 5. Helper: validate feature table
# ------------------------------------------------------------------------------

check_key <- function(
    x,
    object_name
) {

    if (!"key" %in% names(x)) {

        stop(
            object_name,
            " does not contain the required `key` column."
        )
    }


    if (any(is.na(x$key))) {

        stop(
            object_name,
            " contains missing values in `key`."
        )
    }


    if (anyDuplicated(x$key) > 0) {

        duplicated_keys <- unique(
            x$key[
                duplicated(
                    x$key
                )
            ]
        )

        stop(
            object_name,
            " contains duplicated variant keys. Examples: ",
            paste(
                head(
                    duplicated_keys,
                    5
                ),
                collapse = ", "
            )
        )
    }


    message(
        object_name,
        ": ",
        nrow(x),
        " variants; ",
        ncol(x),
        " columns"
    )
}


# ------------------------------------------------------------------------------
# 6. Check input files
# ------------------------------------------------------------------------------

check_file(
    config$base_variants,
    "Base variant"
)

check_file(
    config$gencode_features,
    "GENCODE feature"
)

check_file(
    config$ptbp1_features,
    "PTBP1 feature"
)

check_file(
    config$amino_acid_features,
    "PTC amino-acid feature"
)

check_file(
    config$gene_features,
    "Gene-level feature"
)

check_file(
    config$ptc_geometry_features,
    "PTC geometry feature"
)

check_file(
    config$variant_scores,
    "Variant-score feature"
)

check_file(
    config$motif_features,
    "Motif feature"
)


# ------------------------------------------------------------------------------
# 7. Load base filtered variant table
# ------------------------------------------------------------------------------

message(
    "\n============================================================"
)

message(
    "Building core feature table for: ",
    DATASET
)

message(
    "============================================================\n"
)


base_variants <- readRDS(
    config$base_variants
)

check_key(
    base_variants,
    "Base variant dataset"
)


# ------------------------------------------------------------------------------
# 8. Load feature tables
# ------------------------------------------------------------------------------

feature_tables <- list(

    GENCODE =
        readRDS(
            config$gencode_features
        ),

    PTBP1 =
        readRDS(
            config$ptbp1_features
        ),

    amino_acid =
        readRDS(
            config$amino_acid_features
        ),

    gene =
        readRDS(
            config$gene_features
        ),

    PTC_geometry =
        readRDS(
            config$ptc_geometry_features
        ),

    variant_scores =
        readRDS(
            config$variant_scores
        ),

    motifs =
        readRDS(
            config$motif_features
        )
)


# ------------------------------------------------------------------------------
# 9. Validate feature tables
# ------------------------------------------------------------------------------

message(
    "\nChecking feature tables:\n"
)


for (nm in names(feature_tables)) {

    check_key(
        feature_tables[[nm]],
        nm
    )
}


# ------------------------------------------------------------------------------
# 10. Remove duplicated non-key columns before merging
#
# Some feature tables may contain metadata columns already present in the
# base dataset or in earlier feature tables.
#
# Only newly generated feature columns are retained from each feature table.
# ------------------------------------------------------------------------------

feature_matrix <- base_variants


for (nm in names(feature_tables)) {

    message(
        "\nMerging feature family: ",
        nm
    )


    feature_table <- feature_tables[
        [nm]
    ]


    # Identify columns that already exist in the assembled table.
    duplicated_columns <- intersect(
        names(
            feature_table
        ),
        names(
            feature_matrix
        )
    )


    # `key` is intentionally shared.
    duplicated_columns <- setdiff(
        duplicated_columns,
        "key"
    )


    if (
        length(
            duplicated_columns
        ) > 0
    ) {

        message(
            "  Removing duplicated metadata columns from ",
            nm,
            ": ",
            paste(
                duplicated_columns,
                collapse = ", "
            )
        )


        feature_table <- feature_table %>%
            select(
                -all_of(
                    duplicated_columns
                )
            )
    }


    n_before <- nrow(
        feature_matrix
    )


    feature_matrix <- feature_matrix %>%
        left_join(
            feature_table,
            by = "key"
        )


    if (
        nrow(
            feature_matrix
        ) !=
        n_before
    ) {

        stop(
            "Row count changed while merging ",
            nm,
            ". Check for duplicated keys."
        )
    }


    message(
        "  Current dimensions: ",
        nrow(feature_matrix),
        " rows x ",
        ncol(feature_matrix),
        " columns"
    )
}


# ------------------------------------------------------------------------------
# 11. Final QC
# ------------------------------------------------------------------------------

message(
    "\n============================================================"
)

message(
    "Final assembled core feature table"
)

message(
    "============================================================"
)

message(
    "Dataset: ",
    DATASET
)

message(
    "Variants: ",
    nrow(
        feature_matrix
    )
)

message(
    "Columns: ",
    ncol(
        feature_matrix
    )
)

message(
    "Unique variants: ",
    n_distinct(
        feature_matrix$key
    )
)


# ------------------------------------------------------------------------------
# 12. Missingness summary
# ------------------------------------------------------------------------------

missingness <- data.frame(

    feature =
        names(
            feature_matrix
        ),

    n_missing =
        sapply(
            feature_matrix,
            function(x) {
                sum(
                    is.na(x)
                )
            }
        ),

    pct_missing =
        sapply(
            feature_matrix,
            function(x) {

                round(
                    mean(
                        is.na(x)
                    ) *
                    100,
                    2
                )
            }
        ),

    stringsAsFactors = FALSE
)


missingness <- missingness %>%
    arrange(
        desc(
            pct_missing
        )
    )


# ------------------------------------------------------------------------------
# 13. Create output directory
# ------------------------------------------------------------------------------

dir.create(
    dirname(
        config$output
    ),
    recursive = TRUE,
    showWarnings = FALSE
)


# ------------------------------------------------------------------------------
# 14. Save dataset-specific core feature table
# ------------------------------------------------------------------------------

write_csv(
    feature_matrix,
    config$output,
    na = ""
)


message(
    "\nSaved core feature table:"
)

message(
    config$output
)


# ------------------------------------------------------------------------------
# 15. Save missingness QC table
# ------------------------------------------------------------------------------

missingness_output <- file.path(

    dirname(
        config$output
    ),

    paste0(
        DATASET,
        "_core_feature_missingness.csv"
    )
)


write_csv(
    missingness,
    missingness_output
)


message(
    "Saved missingness summary:"
)

message(
    missingness_output
)


# ------------------------------------------------------------------------------
# 16. TOPMed handoff to TrunCat
#
# Jake's TrunCat workflow expects the main TOPMed table at:
#
#   Model/TrunCat/data/TOPMed_stopgain.csv
#
# Feature modules 08-12 remain separate and are merged later by:
#
#   Model/TrunCat/notebooks/01_data_loading_and_merging.ipynb
# ------------------------------------------------------------------------------

if (
    DATASET ==
    "TOPMed"
) {

    truncat_output <- file.path(
        "Model",
        "TrunCat",
        "data",
        "TOPMed_stopgain.csv"
    )


    dir.create(
        dirname(
            truncat_output
        ),
        recursive = TRUE,
        showWarnings = FALSE
    )


    write_csv(
        feature_matrix,
        truncat_output,
        na = ""
    )


    message(
        "\nTOPMed table additionally saved for TrunCat:"
    )

    message(
        truncat_output
    )
}


# ------------------------------------------------------------------------------
# 17. Final workflow message
# ------------------------------------------------------------------------------

message(
    "\nCore feature assembly complete."
)


if (
    DATASET ==
    "TOPMed"
) {

    message(
        "\nNext TrunCat inputs remain separate:"
    )

    message(
        "  data/annotations/codon_optimality.tsv"
    )

    message(
        "  data/annotations/conservation_medians.csv"
    )

    message(
        "  data/annotations/ejc_occupancy.tsv"
    )

    message(
        "  data/annotations/ptc_aug.tsv"
    )

    message(
        "  data/annotations/readthrough.csv"
    )

    message(
        "\nThese are merged downstream in:"
    )

    message(
        "Model/TrunCat/notebooks/01_data_loading_and_merging.ipynb"
    )
}
