# ==============================================================================
# Shared PTC transcript annotation
#
# Purpose:
#   Derive transcript-level positional and canonical NMD-rule annotations
#   for PTC-producing SNVs.
#
# Shared across:
#   - TOPMed
#   - gnomAD
#   - ClinVar
#   - GREGoR
#
# Prerequisites:
#   1. Dataset-specific extraction and SNV filtering
#   2. ANNOVAR ensGene annotation
#   3. Canonical transcript selection by:
#        01_variant_annotation.R
#   4. GENCODE v26 transcript structure generated by:
#        02_GENCODEv26_transcript_structure.R
#
# Input:
#   - <dataset>_canonical_variant_annotation.rds
#   - gencode_v26_transcript_structure.rds
#
# Output:
#   - <dataset>_PTC_annotated.rds
#
# Features generated:
#   - GENE_ID
#   - coding.pos
#   - mut.exon
#   - length.mutated.exon
#   - first.100
#   - first.200
#   - long.exon
#   - PTC.2.start
#   - PTC.2.end
#   - PTC.2.EJC
#   - last.exon
#   - penultimate.last50bp
#   - penultimate.full
#   - multi_exon
#   - last.EJC
#   - downstream
#   - EJC.downstream
#
# No allele-specific expression outcome or TOPMed-specific confounder
# filtering is performed in this script.
# ==============================================================================


# ------------------------------------------------------------------------------
# 1. Required packages
# ------------------------------------------------------------------------------

library(dplyr)


# ------------------------------------------------------------------------------
# 2. Configuration
# ------------------------------------------------------------------------------

CONFIG <- list(

    # Output of 01_variant_annotation.R
    variant_annotation_file =
        "/path/to/TOPMed_canonical_variant_annotation.rds",

    # Output of 02_GENCODEv26_transcript_structure.R
    transcript_structure_file =
        "/path/to/gencode_v26_transcript_structure.rds",

    # Dataset-specific output
    output_file =
        "/path/to/TOPMed_PTC_annotated.rds"
)


# ------------------------------------------------------------------------------
# 3. Load canonical transcript-specific variant annotation
# ------------------------------------------------------------------------------

variants_canonical <- readRDS(
    CONFIG$variant_annotation_file
)

message(
    "Canonical transcript-specific records loaded: ",
    nrow(variants_canonical)
)


# ------------------------------------------------------------------------------
# 4. Load GENCODE v26 transcript structure
# ------------------------------------------------------------------------------

transcript_structure <- readRDS(
    CONFIG$transcript_structure_file
)


required_structure_columns <- c(
    "txnames",
    "cds_length",
    "cds_exons",
    "exon_count"
)

missing_structure_columns <- setdiff(
    required_structure_columns,
    colnames(transcript_structure)
)

if (length(missing_structure_columns) > 0) {

    stop(
        "Transcript structure file is missing required columns: ",
        paste(
            missing_structure_columns,
            collapse = ", "
        )
    )
}


# ------------------------------------------------------------------------------
# 5. Merge transcript structure by canonical transcript
# ------------------------------------------------------------------------------

variants <- variants_canonical %>%
    left_join(
        transcript_structure,
        by = "txnames"
    )


message(
    "Records with GENCODE v26 transcript structure: ",
    sum(!is.na(variants$cds_exons)),
    " / ",
    nrow(variants)
)


# Retain records for which transcript structure could be resolved.
variants <- variants %>%
    filter(
        !is.na(cds_exons)
    )


# ------------------------------------------------------------------------------
# 6. Parse coding position from ANNOVAR transcript annotation
# ------------------------------------------------------------------------------

extract_coding_position <- function(
    annotation,
    transcript_id
) {

    if (
        is.na(annotation) ||
        is.na(transcript_id)
    ) {
        return(NA_real_)
    }

    fields <- unlist(
        strsplit(
            annotation,
            ":|,"
        )
    )

    transcript_index <- which(
        fields == transcript_id
    )

    # If transcript versions differ, try matching without the version suffix.
    if (length(transcript_index) == 0) {

        fields_no_version <- sub(
            "\\..*$",
            "",
            fields
        )

        transcript_no_version <- sub(
            "\\..*$",
            "",
            transcript_id
        )

        transcript_index <- which(
            fields_no_version ==
                transcript_no_version
        )
    }


    if (length(transcript_index) == 0) {
        return(NA_real_)
    }


    coding_index <-
        transcript_index[1] + 2


    if (
        coding_index >
        length(fields)
    ) {
        return(NA_real_)
    }


    coding_field <- fields[
        coding_index
    ]


    if (!grepl("^c\\.", coding_field)) {
        return(NA_real_)
    }


    # For complex annotation strings, use the first coding coordinate.
    coding_field <- strsplit(
        coding_field,
        "_"
    )[[1]][1]


    coding_position <- suppressWarnings(
        as.numeric(
            gsub(
                "\\D",
                "",
                coding_field
            )
        )
    )


    coding_position
}


variants$coding.pos <- mapply(
    extract_coding_position,
    variants$V3,
    variants$txnames
)


# ------------------------------------------------------------------------------
# 7. Gene identifier
# ------------------------------------------------------------------------------

extract_gene_symbol <- function(annotation) {

    if (
        is.na(annotation) ||
        annotation == ""
    ) {
        return(NA_character_)
    }

    strsplit(
        annotation,
        ":"
    )[[1]][1]
}


variants$GENE_ID <- vapply(
    variants$V3,
    extract_gene_symbol,
    character(1)
)


# ------------------------------------------------------------------------------
# 8. Identify PTC-bearing coding exon
# ------------------------------------------------------------------------------

get_mutated_exon <- function(
    coding_pos,
    cds_exons
) {

    if (
        is.na(coding_pos) ||
        is.na(cds_exons)
    ) {
        return(NA_integer_)
    }


    exon_ends <- as.numeric(
        strsplit(
            as.character(cds_exons),
            ","
        )[[1]]
    )


    hit <- which(
        coding_pos <= exon_ends
    )


    if (length(hit) == 0) {
        return(NA_integer_)
    }


    as.integer(
        hit[1]
    )
}


variants$mut.exon <- mapply(
    get_mutated_exon,
    variants$coding.pos,
    variants$cds_exons
)


# ------------------------------------------------------------------------------
# 9. Length of PTC-bearing coding exon
# ------------------------------------------------------------------------------

get_exon_length <- function(
    mutated_exon,
    cds_exons
) {

    if (
        is.na(mutated_exon) ||
        is.na(cds_exons)
    ) {
        return(NA_real_)
    }


    exon_ends <- as.numeric(
        strsplit(
            as.character(cds_exons),
            ","
        )[[1]]
    )


    if (
        mutated_exon < 1 ||
        mutated_exon >
        length(exon_ends)
    ) {
        return(NA_real_)
    }


    if (mutated_exon == 1) {

        return(
            exon_ends[1]
        )
    }


    exon_ends[
        mutated_exon
    ] -
        exon_ends[
            mutated_exon - 1
        ]
}


variants$length.mutated.exon <- mapply(
    get_exon_length,
    variants$mut.exon,
    variants$cds_exons
)


# ------------------------------------------------------------------------------
# 10. Start-proximal and exon-length annotations
# ------------------------------------------------------------------------------

variants <- variants %>%
    mutate(

        first.100 = case_when(

            is.na(coding.pos) ~
                NA_character_,

            coding.pos <= 100 ~
                "first 100",

            TRUE ~
                "not first 100"
        ),


        first.200 = case_when(

            is.na(coding.pos) ~
                NA_character_,

            coding.pos <= 200 ~
                "first 200",

            TRUE ~
                "not first 200"
        ),


        long.exon = case_when(

            is.na(length.mutated.exon) ~
                NA_character_,

            length.mutated.exon >= 400 ~
                "long.exon",

            TRUE ~
                "not long.exon"
        )
    )


# ------------------------------------------------------------------------------
# 11. PTC-to-EJC distance
#
# PTC.2.EJC is measured from the PTC coding position to the end of the
# PTC-bearing coding exon.
# ------------------------------------------------------------------------------

get_ptc_to_ejc <- function(
    coding_pos,
    mutated_exon,
    cds_exons
) {

    if (
        is.na(coding_pos) ||
        is.na(mutated_exon) ||
        is.na(cds_exons)
    ) {
        return(NA_real_)
    }


    exon_ends <- as.numeric(
        strsplit(
            as.character(cds_exons),
            ","
        )[[1]]
    )


    if (
        mutated_exon < 1 ||
        mutated_exon >
        length(exon_ends)
    ) {
        return(NA_real_)
    }


    exon_ends[
        mutated_exon
    ] -
        coding_pos
}


variants$PTC.2.EJC <- mapply(
    get_ptc_to_ejc,
    variants$coding.pos,
    variants$mut.exon,
    variants$cds_exons
)


# ------------------------------------------------------------------------------
# 12. PTC distance from CDS start/end
# ------------------------------------------------------------------------------

variants <- variants %>%
    mutate(

        PTC.2.start =
            coding.pos,

        PTC.2.end =
            cds_length -
            coding.pos
    )


# ------------------------------------------------------------------------------
# 13. Last-exon annotation
# ------------------------------------------------------------------------------

variants <- variants %>%
    mutate(

        last.exon = case_when(

            is.na(exon_count) |
                is.na(mut.exon) ~
                NA_character_,

            exon_count == 1 ~
                NA_character_,

            exon_count ==
                mut.exon ~
                "lastexon",

            TRUE ~
                "notlastexon"
        )
    )


# ------------------------------------------------------------------------------
# 14. Penultimate-exon last-50-nt annotation
# ------------------------------------------------------------------------------

get_penultimate_last50 <- function(
    coding_pos,
    mutated_exon,
    exon_count,
    cds_exons
) {

    if (
        is.na(coding_pos) ||
        is.na(mutated_exon) ||
        is.na(exon_count) ||
        is.na(cds_exons)
    ) {
        return(NA_character_)
    }


    # Not applicable to single-exon transcripts.
    if (exon_count == 1) {

        return(
            "not penultimate.last50bp"
        )
    }


    # PTC must occur in the penultimate coding exon.
    if (
        exon_count !=
        mutated_exon + 1
    ) {

        return(
            "not penultimate.last50bp"
        )
    }


    exon_ends <- as.numeric(
        strsplit(
            as.character(cds_exons),
            ","
        )[[1]]
    )


    if (length(exon_ends) < 2) {

        return(
            "not penultimate.last50bp"
        )
    }


    penultimate_end <-
        exon_ends[
            length(exon_ends) - 1
        ]


    penultimate_start <-
        if (
            length(exon_ends) > 2
        ) {

            exon_ends[
                length(exon_ends) - 2
            ] + 1

        } else {

            1
        }


    penultimate_length <-
        penultimate_end -
        penultimate_start +
        1


    fifty_position <-
        penultimate_end - 49


    if (
        coding_pos >=
            fifty_position &&
        coding_pos <=
            penultimate_end &&
        penultimate_length >= 50
    ) {

        return(
            "penultimate.last50bp"
        )
    }


    "not penultimate.last50bp"
}


variants$penultimate.last50bp <- mapply(
    get_penultimate_last50,
    variants$coding.pos,
    variants$mut.exon,
    variants$exon_count,
    variants$cds_exons
)


# ------------------------------------------------------------------------------
# 15. Full penultimate-exon indicator
# ------------------------------------------------------------------------------

variants <- variants %>%
    mutate(

        penultimate.full = case_when(

            is.na(exon_count) |
                is.na(mut.exon) ~
                NA_character_,

            exon_count > 1 &
                exon_count ==
                mut.exon + 1 ~
                "penultimate",

            TRUE ~
                "not penultimate"
        )
    )


# ------------------------------------------------------------------------------
# 16. Multi-exon status
#
# This script annotates the property but does not filter on it.
# The TOPMed model-development filter is applied separately.
# ------------------------------------------------------------------------------

variants <- variants %>%
    mutate(

        multi_exon = case_when(

            is.na(exon_count) ~
                NA,

            exon_count > 1 ~
                TRUE,

            TRUE ~
                FALSE
        )
    )


# ------------------------------------------------------------------------------
# 17. Canonical last-EJC classification
#
# Three-level canonical NMD positional classification:
#
#   last.exon
#   penultimate.last50bp
#   upstream
# ------------------------------------------------------------------------------

variants <- variants %>%
    mutate(

        last.EJC = case_when(

            last.exon ==
                "lastexon" ~
                "last.exon",

            penultimate.last50bp ==
                "penultimate.last50bp" ~
                "penultimate.last50bp",

            is.na(last.exon) &
                is.na(
                    penultimate.last50bp
                ) ~
                NA_character_,

            TRUE ~
                "upstream"
        )
    )


# ------------------------------------------------------------------------------
# 18. Binary PTC position relative to last EJC
#
# last exon + penultimate last 50 nt:
#       downstream of last EJC
#
# all other upstream PTCs:
#       upstream of last EJC
# ------------------------------------------------------------------------------

variants <- variants %>%
    mutate(

        downstream = case_when(

            last.EJC %in%
                c(
                    "last.exon",
                    "penultimate.last50bp"
                ) ~
                "downstream of last EJC",

            last.EJC ==
                "upstream" ~
                "upstream of last EJC",

            TRUE ~
                NA_character_
        )
    )


# ------------------------------------------------------------------------------
# 19. Number of downstream exon junctions
#
# Example:
#
#   PTC in last coding exon          -> 0
#   PTC in penultimate coding exon   -> 1
#   PTC two coding exons upstream    -> 2
# ------------------------------------------------------------------------------

variants <- variants %>%
    mutate(

        EJC.downstream = case_when(

            is.na(exon_count) |
                is.na(mut.exon) ~
                NA_integer_,

            TRUE ~
                as.integer(
                    exon_count
                ) -
                as.integer(
                    mut.exon
                )
        )
    )


# ------------------------------------------------------------------------------
# 20. QC checks
# ------------------------------------------------------------------------------

if (
    any(
        variants$EJC.downstream < 0,
        na.rm = TRUE
    )
) {

    warning(
        "Negative EJC.downstream values detected."
    )
}


if (
    any(
        variants$PTC.2.EJC < 0,
        na.rm = TRUE
    )
) {

    warning(
        "Negative PTC.2.EJC values detected."
    )
}


message(
    "\nLast-EJC classification:"
)

print(
    table(
        variants$last.EJC,
        useNA = "ifany"
    )
)


message(
    "\nBinary EJC classification:"
)

print(
    table(
        variants$downstream,
        useNA = "ifany"
    )
)


message(
    "\nNumber of downstream EJCs:"
)

print(
    table(
        variants$EJC.downstream,
        useNA = "ifany"
    )
)


# ------------------------------------------------------------------------------
# 21. Save shared annotated dataset
# ------------------------------------------------------------------------------

variants_annotated <- variants


saveRDS(
    variants_annotated,
    CONFIG$output_file
)


message(
    "\nPTC annotation complete."
)

message(
    "Annotated records: ",
    nrow(variants_annotated)
)

message(
    "Saved: ",
    CONFIG$output_file
)
