# ==============================================================================
# TOPMed PTC transcript annotation and filtering
#
# Purpose:
#   Derive transcript-level and canonical NMD features for TOPMed PTC SNVs
#   and construct the deduplicated model-development dataset.
#
# Input:
#   `variants.features.fr`
#   Generated by the preceding annotation step.
#
# Output:
#   `topmed_annotated`
#
# Major features generated:
#   - coding position
#   - mutated coding exon
#   - mutated exon length
#   - first-100-bp / first-200-bp status
#   - long-exon status
#   - PTC-to-EJC distance
#   - PTC-to-start distance
#   - PTC-to-CDS-end distance
#   - last-exon rule
#   - penultimate-last-50-bp rule
#   - full penultimate-exon status
#
# Additional filters:
#   - multi-exon transcripts
#   - Whole Blood expression > 1 TPM
#   - removal of significant Whole Blood eGenes
#   - removal of imprinted genes
# ==============================================================================


# ------------------------------------------------------------------------------
# 1. Required packages
# ------------------------------------------------------------------------------

library(dplyr)
library(stringr)


# ------------------------------------------------------------------------------
# 2. Configuration
# ------------------------------------------------------------------------------

CONFIG <- list(
    gtex_expression_file =
        "/path/to/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct.txt",

    gtex_egenes_file =
        "/path/to/Whole_Blood.v8.egenes.txt",

    min_whole_blood_tpm = 1
)


# ------------------------------------------------------------------------------
# 3. Initialize dataset
# ------------------------------------------------------------------------------

topmed <- variants.features.fr %>%
    filter(
        !is.na(cds_exons)
    )


# ------------------------------------------------------------------------------
# 4. Parse coding position from ANNOVAR transcript annotation
# ------------------------------------------------------------------------------

extract_coding_position <- function(annotation, transcript_id) {

    fields <- strsplit(
        annotation,
        ":"
    )[[1]]

    transcript_index <- grep(
        fixed = TRUE,
        pattern = transcript_id,
        x = fields
    )

    if (length(transcript_index) == 0) {
        return(NA_real_)
    }

    coding_field <- fields[
        transcript_index[1] + 2
    ]

    if (!grepl("c\\.", coding_field)) {
        return(NA_real_)
    }

    coding_field <- strsplit(
        coding_field,
        "_"
    )[[1]][1]

    as.numeric(
        gsub(
            "\\D",
            "",
            coding_field
        )
    )
}


topmed$coding.pos <- mapply(
    extract_coding_position,
    topmed$V3,
    topmed$txnames
)


# ------------------------------------------------------------------------------
# 5. Gene identifier
# ------------------------------------------------------------------------------

topmed$GENE_ID <- vapply(
    strsplit(
        topmed$V3,
        ":"
    ),
    `[`,
    character(1),
    1
)


# ------------------------------------------------------------------------------
# 6. Mutated coding exon
# ------------------------------------------------------------------------------

get_mutated_exon <- function(
    coding_pos,
    cds_exons
) {

    if (
        is.na(coding_pos) ||
        is.na(cds_exons)
    ) {
        return(NA_real_)
    }

    exon_ends <- as.numeric(
        strsplit(
            as.character(cds_exons),
            ","
        )[[1]]
    )

    which(
        coding_pos <= exon_ends
    )[1]
}


topmed$mut.exon <- mapply(
    get_mutated_exon,
    topmed$coding.pos,
    topmed$cds_exons
)


# ------------------------------------------------------------------------------
# 7. Mutated exon length
# ------------------------------------------------------------------------------

get_exon_length <- function(
    mutated_exon,
    cds_exons
) {

    if (
        is.na(mutated_exon) ||
        is.na(cds_exons)
    ) {
        return(NA_real_)
    }

    exon_ends <- as.numeric(
        strsplit(
            as.character(cds_exons),
            ","
        )[[1]]
    )

    if (mutated_exon == 1) {
        return(exon_ends[1])
    }

    exon_ends[mutated_exon] -
        exon_ends[mutated_exon - 1]
}


topmed$length.mutated.exon <- mapply(
    get_exon_length,
    topmed$mut.exon,
    topmed$cds_exons
)


# ------------------------------------------------------------------------------
# 8. Start-proximal features
# ------------------------------------------------------------------------------

topmed <- topmed %>%
    mutate(

        first.100 = if_else(
            coding.pos <= 100,
            "first 100",
            "not first 100",
            missing = NA_character_
        ),

        first.200 = if_else(
            coding.pos <= 200,
            "first 200",
            "not first 200",
            missing = NA_character_
        ),

        long.exon = case_when(
            is.na(length.mutated.exon) ~ NA_character_,
            length.mutated.exon >= 400 ~ "long.exon",
            TRUE ~ "not long.exon"
        )
    )


# ------------------------------------------------------------------------------
# 9. PTC geometry
# ------------------------------------------------------------------------------

get_ptc_to_ejc <- function(
    coding_pos,
    mutated_exon,
    cds_exons
) {

    if (
        is.na(coding_pos) ||
        is.na(mutated_exon) ||
        is.na(cds_exons)
    ) {
        return(NA_real_)
    }

    exon_ends <- as.numeric(
        strsplit(
            as.character(cds_exons),
            ","
        )[[1]]
    )

    exon_ends[mutated_exon] -
        coding_pos
}


topmed$PTC.2.EJC <- mapply(
    get_ptc_to_ejc,
    topmed$coding.pos,
    topmed$mut.exon,
    topmed$cds_exons
)

topmed <- topmed %>%
    mutate(
        PTC.2.start = coding.pos,
        PTC.2.end =
            cds_length - coding.pos
    )


# ------------------------------------------------------------------------------
# 10. Last-exon rule
# ------------------------------------------------------------------------------

topmed <- topmed %>%
    mutate(
        last.exon = case_when(

            exon_count == 1 ~ NA_character_,

            exon_count == mut.exon ~
                "lastexon",

            TRUE ~
                "notlastexon"
        )
    )


# ------------------------------------------------------------------------------
# 11. Penultimate-last-50-bp rule
# ------------------------------------------------------------------------------

get_penultimate_last50 <- function(
    coding_pos,
    mutated_exon,
    exon_count,
    cds_exons
) {

    if (
        is.na(coding_pos) ||
        is.na(mutated_exon) ||
        is.na(exon_count) ||
        is.na(cds_exons)
    ) {
        return(NA_character_)
    }

    if (exon_count == 1) {
        return(
            "not penultimate.last50bp"
        )
    }

    if (
        exon_count !=
        mutated_exon + 1
    ) {
        return(
            "not penultimate.last50bp"
        )
    }

    exon_ends <- as.numeric(
        strsplit(
            as.character(cds_exons),
            ","
        )[[1]]
    )

    penultimate_end <-
        exon_ends[
            length(exon_ends) - 1
        ]

    penultimate_start <-
        if (
            length(exon_ends) > 2
        ) {
            exon_ends[
                length(exon_ends) - 2
            ]
        } else {
            0
        }

    penultimate_length <-
        penultimate_end -
        penultimate_start

    fifty_position <-
        penultimate_end - 50

    if (
        coding_pos >= fifty_position &&
        coding_pos <= penultimate_end &&
        penultimate_length >= 50
    ) {
        return(
            "penultimate.last50bp"
        )
    }

    "not penultimate.last50bp"
}


topmed$penultimate.last50bp <- mapply(
    get_penultimate_last50,
    topmed$coding.pos,
    topmed$mut.exon,
    topmed$exon_count,
    topmed$cds_exons
)


# ------------------------------------------------------------------------------
# 12. Full penultimate-exon indicator
# ------------------------------------------------------------------------------

topmed <- topmed %>%
    mutate(
        penultimate.full =
            case_when(

                exon_count > 1 &
                exon_count ==
                    mut.exon + 1 ~
                    "penultimate",

                TRUE ~
                    "not penultimate"
            )
    )


# ------------------------------------------------------------------------------
# 13. Allele ratio and NMD outcome
# ------------------------------------------------------------------------------

topmed <- topmed %>%
    mutate(

        ALLELE.RAT =
            1 -
            altCount / totalCount,

        NMD.ESCAPEE =
            case_when(

                ALLELE.RAT >= 0.35 &
                ALLELE.RAT <= 0.65 ~
                    "TRUE",

                ALLELE.RAT > 0.65 ~
                    "FALSE",

                TRUE ~
                    NA_character_
            )
    )


# ------------------------------------------------------------------------------
# 14. Retain one observation per variant
# ------------------------------------------------------------------------------

set.seed(1234)

topmed_unique <- topmed %>%
    group_by(
        key
    ) %>%
    slice_sample(
        n = 1
    ) %>%
    ungroup()


variant_frequency <- topmed %>%
    count(
        key,
        name = "Freq"
    )


topmed_unique <- topmed_unique %>%
    left_join(
        variant_frequency,
        by = "key"
    )


# ------------------------------------------------------------------------------
# 15. Multi-exon transcripts only
# ------------------------------------------------------------------------------

topmed_unique <- topmed_unique %>%
    filter(
        exon_count > 1
    )


# ------------------------------------------------------------------------------
# 16. Whole Blood expression filter
# ------------------------------------------------------------------------------

gtex_expression <- read.table(
    CONFIG$gtex_expression_file,
    header = TRUE,
    sep = "\t",
    stringsAsFactors = FALSE
)

gtex_expression$Gene_ID <- sub(
    "\\..*$",
    "",
    gtex_expression$Name
)

low_expression_genes <-
    gtex_expression %>%
    filter(
        Whole.Blood <=
            CONFIG$min_whole_blood_tpm
    ) %>%
    pull(
        Description
    )

topmed_unique <- topmed_unique %>%
    filter(
        !GENE_ID %in%
            low_expression_genes
    )


# ------------------------------------------------------------------------------
# 17. Remove significant Whole Blood eGenes
# ------------------------------------------------------------------------------

whole_blood_egenes <- read.table(
    CONFIG$gtex_egenes_file,
    sep = "\t",
    header = TRUE,
    stringsAsFactors = FALSE
)

significant_eqtl_variants <-
    whole_blood_egenes %>%
    filter(
        qval <= 0.05
    ) %>%
    mutate(
        variantID =
            sub(
                "_b38$",
                "",
                variant_id
            )
    ) %>%
    pull(
        variantID
    )

topmed_unique <- topmed_unique %>%
    filter(
        !variantID %in%
            significant_eqtl_variants
    )


# ------------------------------------------------------------------------------
# 18. Remove imprinted genes
# ------------------------------------------------------------------------------

imprinted_genes <- c(
    "UTS2",
    "PPIEL",
    "INPP5F_V2",
    "H19",
    "IGF2",
    "KCNQ1",
    "LPAR6",
    "MEG3",
    "RP11-7F17.7",
    "SNRPN",
    "SNHG14",
    "SNURF",
    "UBE3A",
    "ZNF597",
    "ZNF331",
    "L3MBTL1",
    "NAP1L5",
    "FAM50B",
    "PLAGL1",
    "GRB10",
    "MEST"
)

topmed_annotated <- topmed_unique %>%
    filter(
        !GENE_ID %in%
            imprinted_genes
    )


# ------------------------------------------------------------------------------
# 19. Completion summary
# ------------------------------------------------------------------------------

message(
    "Final annotated TOPMed variants: ",
    nrow(topmed_annotated)
)



                                         
